server:
  port: 8048
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: India@123
    url: jdbc:mysql://localhost:3306/testdb
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: stock-service
